### ISSUE TITLE
Do you have a plan that make Variable struct?

### ISSUE THREAD

**Issue by ByungSunBae** [galeone/tfgo#13]
Because of Implementation using tensorflow low-level api..

**Comment by galeone** [comment]
Right now no, no plan to add it directly in Go.

Originally I had the idea of embedding a python interpreter inside tfgo and
use it to create a graph using python (from a Go higher level API). This
allows a complete support for any part of Tensorflow.
But I still have to define everything and I'm looking for collaborators

**Comment by galeone** [comment]
Closing: moved the idea + initial implementation to https://github.com/galeone/rts
