### ISSUE TITLE
loading image, reshaping and feeding to model input

### ISSUE THREAD

**Issue by olablt** [galeone/tfgo#27]
Hey,

I am using python3 + keras in my projects and want to learn go.
What is the right way to prepare the image for inference using tfgo?

Example steps
1. load the rgb image: shape (59, 199, 3)
2. convert to grey: shape (59, 199, 1)
3. resize to (32, 100, 1)
4. reshape to (100, 32, 1)
5. convert to float

then feed the image to
```
results := model.Exec([]tf.Output{
     model.Op("the_output", 0),
 }, map[tf.Output]*tf.Tensor{
     model.Op("the_input", 0): image_jpeg,
 })
```

**Comment by galeone** [comment]
```go
package main

import (
        tg "github.com/galeone/tfgo"
        "github.com/galeone/tfgo/image"
        tf "github.com/tensorflow/tensorflow/tensorflow/go"
       "github.com/tensorflow/tensorflow/tensorflow/go/op"
)
func main() {
        root := tg.NewRoot()
        img := image.Read(root, "path_of_your_image.extension", 3) //shape 59, 199, 3
        img = img.RGBToGrayscale() // shape 59,199,1
        // resize using bilinear interpolation
        img = img.ResizeArea(image.Size{Height: 32, Width: 100})
        imageTensor := img.Value()
        // the tfgo.image package doesn't offer the reshape op, but tensorflow.op package does
        shape := tg.NewTensor(root, tg.Const(root, [3]int32{100, 32, 1}))
        imageTensor = op.Reshape(root, imageTensor, shape)
        // converto to float -> use the tfgo.image package
        newImage := image.NewImage(root, imageTensor)
        floatImage := newImage.ConvertDType(tf.float32, true)
        // extract the tensorflow tensor from the floatImage and you have the input to use in your model
        inputimage := floatImage.Value()
        // [.. other code]
}
```

I haven't tested it (I'm away from my computer right now) but at least it should give you an idea on how to do what you need.

Here some reference you might found useful:

- tfgo.image test: https://github.com/galeone/tfgo/blob/master/image/image_test.go
- godoc of tensorflow.op https://godoc.org/github.com/tensorflow/tensorflow/tensorflow/go/op

Let me know if this help you

**Comment by leondgarse** [comment]
I'm also trying to load an image and feed it to a model, but met some issues:
1. First I use `img.Value()` as an input, but met error `cannot use img.Value() <github.com/tensorflow/tensorflow/tensorflow/go.Output> as type <*github.com/tensorflow/tensorflow/tensorflow/go.Tensor> in map value`
```go
root := tg.NewRoot()
img := image.Read(root, "path/to/image.jpg", 3)
results := model.Exec([]tf.Output{model.Op("the_output", 0)},
        map[tf.Output]*tf.Tensor{model.Op("the_input", 0): img.Value()})
```
2. Then I use `img.Tensor` as an input, but another error `cannot use img.Tensor <*github.com/galeone/tfgo.Tensor> as type <*github.com/tensorflow/tensorflow/tensorflow/go.Tensor> in map value`
```go
root := tg.NewRoot()
img := image.Read(root, "path/to/image.jpg", 3)
results := model.Exec([]tf.Output{model.Op("the_output", 0)},
        map[tf.Output]*tf.Tensor{model.Op("the_input", 0): img.Tensor})
```
3. The only way I found success is converting it to a `tf.Tensor` first, but looks ugly...
```go
root := tg.NewRoot()
img := image.Read(root, "path/to/image.jpg", 3)
results := tg.Exec(root, []tf.Output{img.Value()}, nil, &tf.SessionOptions{})
A, _ := tf.NewTensor(results[0].Value())

results := model.Exec([]tf.Output{model.Op("the_output", 0)},
        map[tf.Output]*tf.Tensor{model.Op("the_input", 0): A})
```

So is this the right way?

**Comment by galeone** [comment]
Yes, although ugly this is a correct way. Currently, I don't remember if this is the *only* way for doing this, but I'm pretty sure I used the very same way before (and it works)

**Comment by leondgarse** [comment]
Thanks, and it helps. :)
