### ISSUE TITLE
how to solve ld: library not found for -ltensorflow

### ISSUE THREAD

**Issue by mullerhai** [galeone/tfgo#30]
mullerhadoop-1:tensorgo muller$ GO111MODULE=on  go get -u -v  github.com/galeone/tfgo
go: finding github.com/galeone/tfgo latest
go: downloading github.com/galeone/tfgo v0.0.0-20191209163057-06635831fc69
go: extracting github.com/galeone/tfgo v0.0.0-20191209163057-06635831fc69
github.com/tensorflow/tensorflow/tensorflow/go
# github.com/tensorflow/tensorflow/tensorflow/go
ld: library not found for -ltensorflow
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by galeone** [comment]
Hi, you have to install in your system the TensorFlow C library.

You can give a look at the CI script to see the complete installation flow: 

https://github.com/galeone/tfgo/blob/master/.travis.yml#L26

Here's the official link to the C pre-compiled library: https://www.tensorflow.org/install/lang_c

Let me know if it helps

**Comment by mullerhai** [comment]
> Hi, you have to install in your system the TensorFlow C library.
> 
> You can give a look at the CI script to see the complete installation flow:
> 
> https://github.com/galeone/tfgo/blob/master/.travis.yml#L26
> 
> Here's the official link to the C pre-compiled library: https://www.tensorflow.org/install/lang_c
> 
> Let me know if it helps

on mac 
brew install tensorflow 
then ok
thx
