### ISSUE TITLE
go get return error  "cannot find package"

### ISSUE THREAD

**Issue by yohaiaz** [galeone/tfgo#31]
anyone can help please. trying go get
go get github.com/tensorflow/tensorflow/tensorflow/go

getting an error "cannot find package..."

I know that's not the appropriate place to ask but what i'm doing wrong ?

I need to load a h5 model into a golang app and make prediction base on this model

tfgo is built on tensorflow/go but we can't go get it
thanks a lot for any help

**Comment by galeone** [comment]
The tensorflow Go package is not a standard Go package, in fact you have to manually download it by your self and switch to the correct branch of the repository.

Have a look at how I do this in the [`.travis.yml`](https://github.com/galeone/tfgo/blob/master/.travis.yml#L28):

```
git clone https://github.com/tensorflow/tensorflow $GOPATH/src/github.com/tensorflow/tensorflow/
pushd $GOPATH/src/github.com/tensorflow/tensorflow/tensorflow/go
git checkout r1.14
go build
```

Let me know if it works for you

**Comment by yohaiaz** [comment]
thanks you so much @galeone
I don't really understand the purposes of the 3 last command line you specified.
I'm trying to work in the same way I'm working with other dependencies.

after running the following line i'm getting the sources at my go path. 
 git clone https://github.com/tensorflow/tensorflow $GOPATH/src/github.com/tensorflow/tensorflow/

now i can import it like this:
import (
tensorflow "github.com/tensorflow/tensorflow/tensorflow/go"
	"github.com/tensorflow/tensorflow/tensorflow/go/op"
)

running the following function give me the error like this

func runModel() {
	// Construct a graph with an operation that produces a string constant.
	s := op.NewScope()
	c := op.Const(s, "Hello from TensorFlow version "+tensorflow.Version())
	graph, err := s.Finalize()
	if err != nil {
		panic(err)
	}

	// Execute the graph in a session.
	sess, err := tensorflow.NewSession(graph, nil)
	if err != nil {
		panic(err)
	}
	output, err := sess.Run(nil, []tensorflow.Output{c}, nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(output[0].Value())
}

error ===>
../../tensorflow/tensorflow/tensorflow/go/saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core" in any of:

/usr/local/Cellar/go/1.13.4/libexec/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core (from $GOROOT)
	/Users/yohai/dev/go/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core (from $GOPATH)

**Comment by yohaiaz** [comment]
also ... a lot of tutorials and post specify running this 2 lines
go get github.com/tensorflow/tensorflow/tensorflow/go
go test github.com/tensorflow/tensorflow/tensorflow/go

this is exactly how I import go packages for use in my code but something going wrong

there is also an opened issue [https://github.com/tensorflow/tensorflow/issues/34580](url) and no one is correcting the issue.

Or maybe I'm missing something ?

**Comment by galeone** [comment]
A lot of tutorials do do **wrong** assumption that the master branch of the TensorFlow repo has a stable Go API. This is false.

The `go get` command, simply clones the tensorflow repository in your go path and checks it out to the `master` branch; but the master branch is not stable for Go :)

So, you have to manually checkout to a branch that has a stable Go API. In the lines above I did it:

1. `git clone https://github.com/tensorflow/tensorflow $GOPATH/src/github.com/tensorflow/tensorflow/`: I'm cloning the tensorflow repo into the correct path (this is equivalent to the go get command)
2. `pushd $GOPATH/src/github.com/tensorflow/tensorflow/tensorflow/go` I'm changing dir and going into the `go` package, inside the tensorflow repo I just cloned
3. `git checkout r1.14` I'm changing branch, from master (unstable) to `r1.14` (tensorflow 1.14) that has a stable and working Go API.
4. `go build` I'm building the go package from sources
5. `go test` If you want to be sure that everything works, run go test (inside the same folder) to test the tensorflow/go package

**Comment by yohaiaz** [comment]
Thanks a lot to @galeone 
it's working now for me
hope for a "go get"-able tensorflow stable go api
