### ISSUE TITLE
[Help needed]input must be 4-dimensional

### ISSUE THREAD

**Issue by leopku** [galeone/tfgo#41]
My code as below,

```go
		model := tg.LoadModel("/opt/models/mobilenet_v2_140_224", []string{"serve"}, nil)
		scope := tg.NewRoot()
		img := image.Read(scope, "/tmp/test.jpeg", 3)
		// img = img.Clone().ResizeArea(image.Size{Height: 224, Width: 224}).Center()
		input := tg.Exec(scope, []tf.Output{img.Value()}, nil, &tf.SessionOptions{})
		tensor, err := tf.NewTensor(input[0].Value())
		if err != nil {
			log.Error().Err(err).Msg("")
		}
		results := model.Exec(
			[]tf.Output{model.Op("StatefulPartitionedCall", 0)},
			map[tf.Output]*tf.Tensor{model.Op("serving_default_input", 0): tensor},
		)
		log.Debug().Interface("results", results[0].Value()).Msg("")

```

Result with:
```
panic: input must be 4-dimensional[573,860,3]
	 [[{{node predict/MobilenetV2/Conv/Relu6}}]]

```

Could some one help me to fixed this issue?

BTW: Same image file and model can be passed using tensorflow official go package.

**Comment by galeone** [comment]
You need to add the batch dimension to the input tensor, in order to correctly feed the model with a (1, 573,860,3) shaped tensor

You can use [tg.Batchify](https://github.com/galeone/tfgo/blob/4089c60ef77a2cbc88a415c2fcd50c22316fba34/ops.go#L28) more or less in this way (code not tested I'm not able to run it right now, I'm sorry)

```go
img := tg.Batchify(scope, []tf.Output{image.Read(scope, "/tmp/test.jpeg", 3)})
```

**Comment by leopku** [comment]
@galeone Big Thanks.

This time error was `panic: Can not squeeze dim[1], expected a dimension of 1, got 44`

core code

```go
		img := tg.Batchify(scope, []tf.Output{image.Read(scope, "/tmp/a72.jpg", 3).Value()})
		input := tg.Exec(scope, []tf.Output{img}, nil, &tf.SessionOptions{})

		tensor, err := tf.NewTensor(input[0].Value())

```

**Comment by galeone** [comment]
I don't know from where the 44 came from - is it an input dimension?

Can you show me the shape of `img` after the batchify call?

**Comment by leopku** [comment]
The shape was `[1, ?, ?, 3]`.

Maybe 44 came from input dimension. 

I wrote the input dimension into a file. Now I'm analyzing it.

**Comment by leopku** [comment]
Finally fixed by comparing codes between which using official go package.

**Comment by galeone** [comment]
Out of curiosity - can you show me how you fixed it?

**Comment by leopku** [comment]
> Out of curiosity - can you show me how you fixed it?

I forgot to resize the image 😭 . Resizing it before batchify can fix it.

This `tfgo` library  is so cool. I really like it.

Finally, thank you for your reply and this amazing library.

**Comment by galeone** [comment]
Thank you for the kind words!! :smiley:

**Comment by pengdengke** [comment]
> > @leopku I also encountered the same problem, do you use `readImg.ResizeArea(image.Size{Height:224, Width:224})`？
> 
> Yes.

Thank you, it helped me a lot
