### ISSUE TITLE
Update both repos to TF2.4.1

### ISSUE THREAD

**Issue by Dilshat** [galeone/tfgo#50]
Seems the tfgo and the fork of the official tensorflow repo are at 2.4.0-rc
@galeone Are you going to update to 2.4.1?

**Comment by galeone** [comment]
Sure, as soon as the TensorFlow team releases the prebuilt C libraries: https://www.tensorflow.org/install/lang_c

Currently they still have 2.4.0 out

**Comment by Dilshat** [comment]
I tired to get 2.4.1 and it worked
`curl -OL https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.4.1.tar.gz`

**Comment by SysuJayce** [comment]
Any updates？

**Comment by galeone** [comment]
Maybe it's time to update to 2.5 :+1: 

I'll try to do this update by the end of this week, but I'm crazy busy these days and I can't guarantee I'll be able to do it

**Comment by galeone** [comment]
Done, The [galeone/tensorflow](https://github.com/galeone/tensorflow/tree/r2.5-go/tensorflow/go) has the r2-5-go branch that contains the compiled protobuf (manually fixed :sweat_smile: ) that allow to go-get tensorflow.

tfgo needs no change, now it just depends on the new tensorflow version.

**Comment by Dilshat** [comment]
Thanks a lot @galeone !
As soon as you release a new version, we can start using it

**Comment by galeone** [comment]
@Dilshat it's already released, master branch contains all you need for using tf2.5

**Comment by Dilshat** [comment]
@galeone I meant the fork tensorflow repo

**Comment by galeone** [comment]
> @galeone I meant the fork tensorflow repo

Yup it has been updated too!

tfgo now depends on the new branch I created in the fork: https://github.com/galeone/tensorflow/tree/r2.5-go

You can use tfgo (that automatically downalods the fork in the correct branch) or directly the branch `r2.5-go` of the fork :+1:
