### ISSUE TITLE
Backward Compatibility

### ISSUE THREAD

**Issue by SysuJayce** [galeone/tfgo#52]
Hello galeone, thanks for your work. Below is some questions confusing me.

1. Since you have updated to tf2.5, I wonder if this version compatible with tf2.4.1 or older tf version.

2. What's the performance diff between tfgo and tensorflow go api?

3. What will we get apart from convenience if we use tfgo rather than the official api?

**Comment by galeone** [comment]
1. Yes, tfgo is compatible with every TensorFlow 2.x version. There's no API change in the Go bindings API (for now). However, the fact is that the TensorFlow official Go bindings are not Go-gettable and there's the need to use my fork that, instead, just works. 
2. (and 3) There's no performance difference. With tfgo you can easily define static graphs (with method chaining, differently from the official tensorflow API that forces you to write unpleasant code) and also load SavedModels - the performance are exactly the same, tfgo is just easy to use.

**Comment by SysuJayce** [comment]
Great!

Therefore, we can use simply replace the official tf go binding with tfgo for any tf2.x version.

That's awesome!
Thanks!
