### ISSUE TITLE
LeNetDropout/softmax_linear/Identity

### ISSUE THREAD

**Issue by cbhanu** [galeone/tfgo#6]
results := model.Exec([]tf.Output{
                model.Op("LeNetDropout/softmax_linear/Identity", 0),

In this line, if we are using our own .pb model, how to find out the identifier for it ?

**Comment by galeone** [comment]
In that line, you're looking for the output node of your classification network. In my case, it was `LeNetDropout/softmax_linear/Identity`.

To find the name of your output node, you just have to use python, define your network and get the `.name` property of the output tensor. For example

```python
inputs = tf.placeholder(tf.float32, shape=(None,10,10,1), name="input_")
out = tf.layers.conv2d(inputs, 10,(10,10))
print(out.name)
```

In general, when using `model.Op` you have to know the name of the operation you want to execute (and you're not limited to execute only the output node, you can execute any node in the graph just by knowing its name).
