### ISSUE TITLE
loading model

### ISSUE THREAD

**Issue by Kur-Ich** [galeone/tfgo#64]
Hi, 

I have a `saved_model.pb` file in the dir path. However, I'm getting the following error when trying to load the model: `Could not find SavedModel .pb or .pbtxt at supplied export directory path`. I've saved the model with the `tf.saved_model.save` function as recommended in Python. 

When using the `saved_model_cli` tool the tag is set to "serve": `MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:`

I also get the following error when running the program:
`/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 3 (>= sh_info of 3)
`

Any ideas for common causes?

**Comment by Kur-Ich** [comment]
Found it, my path was defined as `~/..` (Linux home dir). When I changed the path to a relative path it worked. Probably the ~ symbol was the problem.

**Comment by galeone** [comment]
Glad you figured it out!
