### ISSUE TITLE
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by Dabnis** [galeone/tfgo#65]
with  go get github.com/galeone/tfgo I am getting:

cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

**Comment by galeone** [comment]
TensorFlow + Go + Windows it's not officially supported by Google.

We were talking about it here: https://github.com/galeone/tfgo/issues/46#issuecomment-774724977

Maybe you can find some info, but I can't help you in any way because I don't even have a Windows machine.
