### ISSUE TITLE
Can I use tfgo for tensorflow 2.11.x?

### ISSUE THREAD

**Issue by tanvir-retailai** [galeone/tfgo#81]
Hi @galeone,

I would like to try `tfgo` in a production setup with tensorflow 2.11.0. I found that your installation guide is pointing to tensorflow version 2.9.1. Any suggestion highly appreciated.

**Comment by galeone** [comment]
It shouldn't be a problem. The C library is compatible, but there could be
some operations that haven't been mapped to the Go bindings.

In a few days I'll upgrade the TensorFlow' fork go-gettable to TensorFlow
2.11 (or whatever is the latest version) so we can get sure that everything
works fine and the support is complete

**Comment by tanvir-retailai** [comment]
@galeone Thanks for your prompt reply. The current stable version of TensorFlow is 2.11.0. 

It would be really helpful if you release the `TensorFlow fork go-gettable` to TensorFlow 2.11.0. I will wait for the release and will test it intensively. For the time being I am going to close this issue then.

many thanks
