### ISSUE TITLE
Convert opencv's `mat` to tfgo's `tensor`

### ISSUE THREAD

**Issue by modanesh** [galeone/tfgo#82]
I'm using [gocv](https://github.com/hybridgroup/gocv) to read an image from file and apply some preprocessing steps. The result of these steps is a variable of type `gocv.Mat`. Now I want to feed this image to my model using tfgo. However, when I try to create a new tensor, I get the error that it's an `unsupported type`. I'm wondering how one could convert a `gocv.Mat` variable to a `tfgo.NewTensor`? 

Any help is much appreciated.

**Comment by galeone** [comment]
Hi, I'm not familiar with gocv, but I guess you just need a way to extract the raw byte representation from the `gocv.Mat` type, and create the new tensor. Be careful, that you want to extract not the RGB representation, but a compressed representation (e.g. the PNG image, thus the png headers + the png content).

Anyway, I do recommend to user the TensorFlow primitives instead of mixing gocv with tfgo.

**Comment by modanesh** [comment]
Thanks. `gocv` is basically the OpenCV in Go. I have the following preprocessing steps using `gocv` in Go and `cv2` in python. Doing these, the `r_img`s in both cases are exactly the same. Do you think these steps are reproducible using tfgo?

```golang
img := gocv.IMRead(filename, gocv.IMReadColor)
defer img.Close()

c_img := gocv.NewMat()
defer c_img.Close()
gocv.CvtColor(img, &c_img, gocv.ColorBGRToRGB)

r_img := gocv.NewMat()
defer r_img.Close()
gocv.Resize(c_img, &r_img, image.Point{112, 112}, 0, 0, gocv.InterpolationLinear)
```

and the python equivalent:

```python
img = cv2.imread(filename)
c_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
r_img = cv2.resize(c_img, (112, 112))
```

**Comment by galeone** [comment]
Yes, have a look at the [example code in the README](https://github.com/galeone/tfgo#computer-vision-using-data-flow-graph).
Using the "github.com/galeone/tfgo/image" package, you can read the image, resize it, get a tensor out of it, and save it

**Comment by modanesh** [comment]
Great. Thanks for the help.

**Comment by modanesh** [comment]
Using the `Value()` from the `galeone/tfgo/image` package, I'm getting the following error:
`Cannot use 'r_img.Value()' (type tf.Output) as the type *tf.Tensor`

This is how I feed the image to the model:
```go
root := tg.NewRoot()
img := image.Read(root, filename, 3)
r_img := img.CropAndResize(image.Box{Start: image.Point{X: 0.0, Y: 0.0},
	End: image.Point{X: 1.0, Y: 1.0}},
	image.Size{Height: 112, Width: 112})

model := tg.LoadModel("./model_pb", []string{"serve"}, nil)

qmf_results := model.Exec([]tf.Output{
	model.Op("PartitionedCall", 0),
		}, map[tf.Output]*tf.Tensor{
	qmf_model.Op("serving_default_input.1", 0): r_img.Value(),
})
```

**Comment by modanesh** [comment]
Hey @galeone :)
Any idea about the above error?

**Comment by modanesh** [comment]
The `Cannot use 'r_img.Value()' (type tf.Output) as the type *tf.Tensor` has already been discussed in #27, so closing this one.
