### ISSUE TITLE
Choose output layer of model . 

### ISSUE THREAD

**Issue by johntharian28** [galeone/tfgo#87]
I have been trying to load a mobilenet model and use it to create a vector embedding of an image. Is such kind of operations not possible with tf-go ?

**Comment by galeone** [comment]
Hi, yes this is possible. Just export the model as a SavedModel. Use `saved_model_cli`  to see all the available inputs/outputs and use tfgo to load the model, feed the model using the correct input, and fetch from the correct output.

If mobilenet (that I imagine you download from somewhere) doesn't come with the output layer you need (some layer to treat as output for getting the vector embeddings) you need to use Python to export a new SavedModel and explicitly set your desired layer as output
