### ISSUE TITLE
Can't load model

### ISSUE THREAD

**Issue by remotejob** [galeone/tfgo#9]
I create model using http://opennmt.net
result of saved_model_cli show

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['length'] tensor_info:
        dtype: DT_INT32
        shape: (-1)
        name: Placeholder_1:0
    inputs['tokens'] tensor_info:
        dtype: DT_STRING
        shape: (-1, -1)
        name: Placeholder:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['alignment'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4, -1, -1)
        name: seq2seq/decoder/Reshape_7:0
    outputs['length'] tensor_info:
        dtype: DT_INT32
        shape: (-1, 4)
        name: seq2seq/decoder/decoder_1/while/Exit_19:0
    outputs['log_probs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4)
        name: seq2seq/decoder/decoder_1/while/Exit_14:0
    outputs['tokens'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 4, -1)
        name: seq2seq/index_to_string_Lookup:0
  Method name is: tensorflow/serving/predict`
```

But I can't load model

```
goroutine 1 [running]:
github.com/galeone/tfgo.LoadModel(0x4ce6a9, 0xa, 0xc00003c778, 0x1, 0x1, 0x0, 0x49937f)
        /exwindoz/home/juno/gowork/src/github.com/galeone/tfgo/model.go:35 +0x11d
main.main()
        /exwindoz/home/juno/gowork/src/github.com/remotejob/tensorflow-export-import-example/example.go:13 +0x77
exit status 2
```

**Comment by galeone** [comment]
Hi, can you post the complete go code + the output of `protoc --decode_raw < your_model.pb`

**Comment by remotejob** [comment]
Looks like mistake more relate to tensorflow API
`panic: Op type not registered 'GatherTree' in binary running on lenovo. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
`
my example.go
`func main() {

	model := tg.LoadModel("MODEL", []string{"serve"}, &tf.SessionOptions{})
	log.Println(model)

}
`
Anyway any help appreciated
[protocraw.txt](https://github.com/galeone/tfgo/files/2523332/protocraw.txt)

**Comment by remotejob** [comment]
Probably for now I will use Python, unfortunately.:(
